version: 2
updates:
  # Проверка Python зависимостей
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "⬆️"
    # Настройка безопасности - автоматически создает PR для уязвимостей
    groups:
      security-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Если используете GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
